sonar.projectKey=mrembiasz-blog
sonar.projectName=mrembiasz-blog
sonar.sourceEncoding=UTF-8

sonar.sources=src,terraform,deploy,tests
sonar.exclusions=dist/**,.astro/**,node_modules/**,terraform/.terraform/**,deploy/backend-lambdas/**
