apiVersion: v1
kind: Pod
spec:
  containers:
    - name: node
      image: mcr.microsoft.com/playwright:v1.62.1-noble
      command:
        - cat
      tty: true
    - name: terraform
      image: hashicorp/terraform:1.13
      command:
        - cat
      tty: true
    - name: go
      image: golang:1.25
      command:
        - cat
      tty: true
    - name: aws
      image: amazon/aws-cli:2.28.21
      command:
        - cat
      tty: true
