apiVersion: v1
kind: Pod
spec:
  containers:
    - name: node
      image: mcr.microsoft.com/playwright:v1.62.1-noble
      env:
        - name: npm_config_cache
          value: /cache/npm
      volumeMounts:
        - name: repo-cache
          mountPath: /cache
      command:
        - cat
      tty: true
    - name: terraform
      image: hashicorp/terraform:1.13
      env:
        - name: TF_PLUGIN_CACHE_DIR
          value: /cache/terraform/plugins
      volumeMounts:
        - name: repo-cache
          mountPath: /cache
      command:
        - cat
      tty: true
    - name: go
      image: kerbatek/mrembiasz-blog:go-1.25-zip
      env:
        - name: GOMODCACHE
          value: /cache/go/pkg/mod
        - name: GOCACHE
          value: /cache/go/build
      volumeMounts:
        - name: repo-cache
          mountPath: /cache
      command:
        - cat
      tty: true
    - name: sonarqube
      image: sonarsource/sonar-scanner-cli:latest
      command:
        - cat
      tty: true
    - name: aws
      image: amazon/aws-cli:2.28.21
      command:
        - cat
      tty: true
  volumes:
    - name: repo-cache
      persistentVolumeClaim:
        claimName: mrembiasz-blog-cache
