pipeline {
  agent {
    kubernetes {
      defaultContainer 'node'
      yamlFile 'deploy/jenkins/agent-pod.yaml'
    }
  }

  environment {
    TF_IN_AUTOMATION = 'true'
  }

  options {
    disableConcurrentBuilds()
  }

  stages {
    stage('Build Astro') {
      steps {
        sh 'deploy/scripts/build-astro.sh'
      }
    }

    stage('Terraform Plan') {
      environment {
        AWS_ROLE_ARN = 'arn:aws:iam::047588357922:role/mrembiasz-blog-jenkins-plan'
      }
      steps {
        container('terraform') {
          withCredentials([file(credentialsId: 'aws-oidc-token', variable: 'AWS_WEB_IDENTITY_TOKEN_FILE')]) {
            sh 'deploy/scripts/terraform-plan.sh'
          }
        }
      }
    }

    stage('Terraform Apply') {
      when {
        branch 'main'
      }
      environment {
        AWS_ROLE_ARN = 'arn:aws:iam::047588357922:role/mrembiasz-blog-jenkins-deploy'
      }
      steps {
        container('terraform') {
          withCredentials([file(credentialsId: 'aws-oidc-token', variable: 'AWS_WEB_IDENTITY_TOKEN_FILE')]) {
            sh 'deploy/scripts/terraform-apply.sh'
          }
        }
      }
    }

    stage('Deploy Static Site') {
      when {
        branch 'main'
      }
      environment {
        AWS_ROLE_ARN = 'arn:aws:iam::047588357922:role/mrembiasz-blog-jenkins-deploy'
      }
      steps {
        container('aws') {
          withCredentials([file(credentialsId: 'aws-oidc-token', variable: 'AWS_WEB_IDENTITY_TOKEN_FILE')]) {
            sh 'deploy/scripts/deploy-static-site.sh'
          }
        }
      }
    }
  }

  post {
    success {
      archiveArtifacts artifacts: 'dist/**, terraform/tfplan, terraform/tfplan.txt', fingerprint: true
    }
  }
}
